import {test,expect,type Page} from '@playwright/test';
async function walk(page:Page,x:number,y:number){const initialWorld=await page.locator(".world-canvas").getAttribute("data-world-id");const canvas=page.locator('.world-canvas canvas');await canvas.scrollIntoViewIfNeeded();const b=await canvas.boundingBox(),d=await page.locator('.world-canvas').evaluate(el=>({...((el as HTMLElement).dataset)}));await page.mouse.click(b!.x+(x*32-Number(d.cameraScrollX))*Number(d.cameraZoom),b!.y+(y*32-Number(d.cameraScrollY))*Number(d.cameraZoom));await expect.poll(async()=>{const p=await page.locator('.world-canvas').evaluate(el=>({x:Number((el as HTMLElement).dataset.authoritativeX),y:Number((el as HTMLElement).dataset.authoritativeY)}));if(await page.locator(".world-canvas").getAttribute("data-world-id")!==initialWorld)return 0;return Math.hypot(p.x-x,p.y-y);},{timeout:7000}).toBeLessThan(.35);}
test('individual asylum entry, map, charger, projector static and refresh recovery',async({browser,page})=>{
 test.setTimeout(100000);const context=await browser.newContext(),friend=await context.newPage(),errors:string[]=[];for(const p of [page,friend])p.on('pageerror',e=>errors.push(e.message));
 try{
 const name='Asylum '+Date.now();await page.goto('/');await page.getByLabel('Your name',{exact:true}).fill('Explorer');await page.getByLabel('Home name',{exact:true}).fill(name);await page.getByLabel('Choose a private PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Create & enter home'}).click();await expect(page.locator('.connection')).toHaveText('Connected');
 const id=await page.evaluate(async n=>(await(await fetch('/api/homes')).json()).homes.find((h:{name:string})=>h.name===n).id,name);
 await friend.goto('/');await friend.getByLabel('Your name',{exact:true}).fill('Camper');await friend.getByRole('button',{name:'Join friends',exact:true}).click();await friend.getByLabel('Home ID',{exact:true}).fill(id);await friend.getByLabel('Room PIN',{exact:true}).fill('123456');await friend.getByRole('button',{name:'Join your friends'}).click();await expect(friend.locator('.connection')).toHaveText('Connected');
 await page.getByLabel('Toggle map').click();await expect(page.getByRole('img',{name:'Map of friends, campfire and race cabin'})).toBeVisible();await page.getByLabel('Toggle map').click();
 await expect(page.getByRole('button',{name:'▣ Watch together'})).toHaveCount(0);
 await walk(page,24,27);await walk(page,27,24);for(const x of [34,41,48,55,62,69])await walk(page,x,24);await walk(page,69,17);await page.locator(".world-canvas").focus();await page.keyboard.down("ArrowUp");await page.waitForTimeout(1050);await page.keyboard.up("ArrowUp");
 await expect(page.locator('.world-canvas')).toHaveAttribute('data-world-id','asylum');await expect(friend.locator('.world-canvas')).toHaveAttribute('data-world-id','forest');
 await friend.getByLabel('Toggle map').click();await expect(friend.locator('.map-card')).toContainText('Explorer · Asylum');
 await expect(page.locator('.creepy-static')).toBeVisible();await page.screenshot({path:'tests/e2e/artifacts/asylum-interior.png',fullPage:true});
 await walk(page,16.5,9.5);await expect(page.locator('.world-canvas')).toHaveAttribute('data-seat-id','charger-seat');await expect(page.locator('.world-canvas')).toHaveAttribute('data-flashlight-battery',/0\.99|1/);
 await page.getByRole('button',{name:'▣ Watch together'}).click();await expect(page.getByLabel('Video link')).toBeVisible();await expect(page.getByText('The asylum projector')).toBeVisible();await page.getByRole('button',{name:'Close shared screen'}).click();
 await page.reload();await expect(page.locator('.connection')).toHaveText('Connected');await expect(page.locator('.world-canvas')).toHaveAttribute('data-world-id','asylum');await expect(page.locator('.world-canvas')).toHaveAttribute('data-seat-id','charger-seat');
 await walk(page,10,16);await page.locator(".world-canvas").focus();await page.keyboard.down("ArrowDown");await page.waitForTimeout(600);await page.keyboard.up("ArrowDown");await expect(page.locator('.world-canvas')).toHaveAttribute('data-world-id','forest');await expect(friend.locator('.world-canvas')).toHaveAttribute('data-world-id','forest');expect(errors).toEqual([]);
 }finally{await context.close();}
});
test('dark theme persists and mobile movement arrows remain opaque',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByLabel('Your name',{exact:true}).fill('Mobile');await page.getByLabel('Home name',{exact:true}).fill('Mobile '+Date.now());await page.getByLabel('Choose a private PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Create & enter home'}).click();await expect(page.locator('.connection')).toHaveText('Connected');await expect(page.locator('main')).toHaveClass(/dark-theme/);const arrow=page.getByLabel('Move up');await expect(arrow).toBeVisible();expect(await arrow.evaluate(el=>getComputedStyle(el).opacity)).toBe('1');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByLabel('Color theme').selectOption('light');await page.reload();await expect(page.locator('.connection')).toHaveText('Connected');await expect(page.locator('main')).not.toHaveClass(/dark-theme/);
});
test('world fits wide and short screens; movement arrows do not scroll the page',async({page})=>{
 await page.setViewportSize({width:1920,height:900});await page.goto('/');await page.getByLabel('Your name',{exact:true}).fill('Keyboard');await page.getByLabel('Home name',{exact:true}).fill('Viewport '+Date.now());await page.getByLabel('Choose a private PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Create & enter home'}).click();await expect(page.locator('.connection')).toHaveText('Connected');await expect(page.locator('.world-canvas')).toHaveAttribute('data-seat-id',/camp-seat-/);
 for(const size of [{width:1920,height:900},{width:1366,height:768},{width:1440,height:650}]){await page.setViewportSize(size);await expect.poll(async()=>{const b=await page.locator('.world-canvas').boundingBox();return b!.height;}).toBeLessThan(size.height-200);await page.locator('.world-canvas').focus();const scroll=await page.evaluate(()=>scrollY),beforeY=Number(await page.locator('.world-canvas').getAttribute('data-authoritative-y'));await page.keyboard.down('ArrowDown');await page.waitForTimeout(400);await page.keyboard.up('ArrowDown');expect(await page.evaluate(()=>scrollY)).toBe(scroll);expect(Number(await page.locator('.world-canvas').getAttribute('data-authoritative-y'))).toBeGreaterThan(beforeY+.3);}
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByLabel('Color theme').focus();expect(await page.getByLabel('Color theme').evaluate(el=>el.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true})))).toBe(true);
});
