import { test, expect } from "@playwright/test";

test("F toggles flashlight once per press and leaves typing, buttons and modal controls accessible", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Your name", { exact: true }).fill("Hotkey QA");
  await page.getByLabel("Home name", { exact: true }).fill("Hotkeys " + Date.now());
  await page.getByLabel("Choose a private PIN", { exact: true }).fill("123456");
  await page.getByRole("button", { name: /Create & enter home/ }).click();
  await expect(page.locator(".connection")).toHaveText("Connected");
  const world = page.locator(".world-canvas");
  await expect(world).toHaveAttribute("data-flashlight-on", "true");
  await world.focus();
  await page.keyboard.down("f");
  await expect(world).toHaveAttribute("data-flashlight-on", "false");
  await page.keyboard.down("f");
  await page.waitForTimeout(200);
  await expect(world).toHaveAttribute("data-flashlight-on", "false");
  await page.keyboard.up("f");
  await page.keyboard.press("f");
  await expect(world).toHaveAttribute("data-flashlight-on", "true");
  await page.getByRole("button", { name: "Toggle map" }).focus();
  await page.keyboard.press("f");
  await expect(world).toHaveAttribute("data-flashlight-on", "false");
  const flashlight = page.locator('button[aria-keyshortcuts="F"]');
  await expect(flashlight).toHaveAttribute("title", "Toggle flashlight (F)");
  await flashlight.focus(); await page.keyboard.press("Space");
  await expect(world).toHaveAttribute("data-flashlight-on", "true");
  await world.focus(); await page.keyboard.press("Enter");
  const chat = page.getByLabel("Message friends");
  await expect(chat).toBeFocused();
  await page.keyboard.press("f"); await expect(chat).toHaveValue("f");
  await page.waitForTimeout(150);
  await expect(world).toHaveAttribute("data-flashlight-on", "true");
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await page.keyboard.press("f"); await page.waitForTimeout(150);
  await expect(world).toHaveAttribute("data-flashlight-on", "true");
  await page.keyboard.press("Escape");
  await world.focus(); await page.keyboard.press("f");
  await expect(world).toHaveAttribute("data-flashlight-on", "false");
  expect(errors).toEqual([]);
});
