import {test,expect,type Page} from '@playwright/test';
async function enter(page:Page){await page.goto('/');await page.getByLabel('Your name',{exact:true}).fill('Keyboard QA');await page.getByLabel('Home name',{exact:true}).fill('Controls '+Date.now());await page.getByLabel('Choose a private PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Create & enter home'}).click();const world=page.locator('.world-canvas');await expect(world).toHaveAttribute('data-authoritative-x',/[0-9]/);await world.scrollIntoViewIfNeeded();await world.focus();return world;}
async function position(page:Page){return page.locator('.world-canvas').evaluate(el=>{const d=(el as HTMLElement).dataset;return{x:Number(d.authoritativeX),y:Number(d.authoritativeY)};});}
async function screen(page:Page,point:{x:number;y:number}){return page.locator('.world-canvas').evaluate((el,p)=>{const d=(el as HTMLElement).dataset,b=el.querySelector('canvas')!.getBoundingClientRect();return{x:b.x+(p.x*32-Number(d.cameraScrollX))*Number(d.cameraZoom),y:b.y+(p.y*32-Number(d.cameraScrollY))*Number(d.cameraZoom)};},point);}
async function stationary(page:Page,before:{x:number;y:number}){await page.waitForTimeout(450);const after=await position(page);expect(Math.hypot(after.x-before.x,after.y-before.y)).toBeLessThan(.05);await expect(page.locator('.world-canvas')).toHaveAttribute('data-move-target-x','');}
for(const width of [1440,390])test(`mouse aims and never travels; keyboard and focus authority ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const world=await enter(page),initial=await position(page);
 for(const delta of [{x:2,y:0,face:'right'},{x:-6,y:-4,face:'left'},{x:0,y:2,face:'down'},{x:0,y:-2,face:'up'}]){const p=await screen(page,{x:initial.x+delta.x,y:initial.y+delta.y});await page.mouse.move(p.x,p.y);await expect(world).toHaveAttribute('data-authoritative-facing',delta.face);await page.mouse.click(p.x,p.y);await stationary(page,initial);}
 if(width===390){await page.getByRole('button',{name:'Move right',exact:true}).click();await stationary(page,initial);await world.focus();}
 await page.keyboard.press('KeyE');await stationary(page,initial);
 await world.focus();await page.keyboard.down('KeyD');await page.waitForTimeout(220);await page.keyboard.up('KeyD');await expect.poll(async()=>(await position(page)).x).toBeGreaterThan(initial.x+.3);
 let before=await position(page);await page.keyboard.down('ArrowDown');await page.waitForTimeout(220);await page.keyboard.up('ArrowDown');await expect.poll(async()=>(await position(page)).y).toBeGreaterThan(before.y+.3);
 await page.waitForTimeout(200);before=await position(page);await page.keyboard.press('Control+KeyW');await stationary(page,before);
 await page.keyboard.press('/');const chat=page.getByLabel('Message friends');await expect(chat).toBeFocused();before=await position(page);await chat.fill('wasd e mouse focus');await page.keyboard.press('ArrowLeft');await stationary(page,before);await page.keyboard.press('Escape');await expect(world).toBeFocused();
 await page.locator('.game-menu-toggle').click();await page.getByRole('button',{name:'Close game menu'}).click();await expect(world).toBeFocused();
 await page.keyboard.down('KeyS');await page.waitForTimeout(160);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.keyboard.up('KeyS');await page.waitForTimeout(200);before=await position(page);await stationary(page,before);expect(errors).toEqual([]);
});
test('actual touch retains floor travel, while a mouse on the same touch-capable device does not',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();try{const world=await enter(page),initial=await position(page),target={x:initial.x+1.6,y:initial.y+1.3},point=await screen(page,target);await page.touchscreen.tap(point.x,point.y);await expect.poll(async()=>Math.hypot((await position(page)).x-target.x,(await position(page)).y-target.y),{timeout:8000}).toBeLessThan(.25);await page.waitForTimeout(150);const before=await position(page),mouse=await screen(page,{x:before.x-1.5,y:before.y});await page.mouse.click(mouse.x,mouse.y);await stationary(page,before);await expect(world).toHaveAttribute('data-move-target-y','');
 const cdp=await context.newCDPSession(page),move=(await page.getByRole('button',{name:'Move right',exact:true}).boundingBox())!,sprint=(await page.getByRole('button',{name:'Hold to sprint',exact:true}).boundingBox())!,touchBefore=await position(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:move.x+move.width/2,y:move.y+move.height/2},{id:2,x:sprint.x+sprint.width/2,y:sprint.y+sprint.height/2}]});await page.waitForTimeout(400);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(async()=>(await position(page)).x).toBeGreaterThan(touchBefore.x+.5);expect(Number(await world.getAttribute('data-stamina'))).toBeLessThan(.99);await page.waitForTimeout(200);const stopped=await position(page);await stationary(page,stopped);await expect(world).toHaveAttribute('data-sprinting','false');}finally{await context.close();}
});
