import { test, expect, type Page } from "@playwright/test";
async function create(page: Page) {
    const name = "Worlds " + Date.now();
    await page.goto("/");
    await page.getByLabel("Your name", { exact: true }).fill("Ari");
    await page.getByLabel("Home name", { exact: true }).fill(name);
    await page.getByLabel("Choose a private PIN", { exact: true }).fill("123456");
    await page.getByRole("button", { name: "Create & enter home" }).click();
    await expect(page.locator(".connection")).toHaveText("Connected");
    await page.locator(".world-canvas canvas").waitFor();
    return page.evaluate(async (name) => (await (await fetch("/api/homes")).json()).homes.find((h: {
        name: string;
    }) => h.name === name).id, name);
}
async function join(page: Page, id: string) { await page.goto("/"); await page.getByLabel("Your name", { exact: true }).fill("Remy"); await page.getByRole("button", { name: "Join friends", exact: true }).click(); await page.getByLabel("Home ID", { exact: true }).fill(id); await page.getByLabel("Room PIN", { exact: true }).fill("123456"); await page.getByRole("button", { name: "Join your friends" }).click(); await expect(page.locator(".connection")).toHaveText("Connected"); }
test("campsite-only friends have distinct seats, roast, sleep rendering and restore on refresh",async({browser,page})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));const context=await browser.newContext(),second=await context.newPage();second.on("pageerror",e=>errors.push(e.message));
 try{const id=await create(page);await join(second,id);await expect(page.locator(".world-canvas")).toHaveAttribute("data-seat-id",/camp-seat-/);await expect(second.locator(".world-canvas")).toHaveAttribute("data-seat-id",/camp-seat-/);expect(await page.locator(".world-canvas").getAttribute("data-seat-id")).not.toBe(await second.locator(".world-canvas").getAttribute("data-seat-id"));
 await page.getByRole("button",{name:"☷ Worlds"}).click();await expect(page.getByRole("button",{name:/The reading lounge/})).toHaveCount(0);await expect(page.getByRole("button",{name:/Midnight Pines/})).toBeDisabled();await page.getByRole("button",{name:"Close worlds"}).click();
 await page.getByRole("button",{name:"☺ Emotes"}).click();await page.getByRole("button",{name:/Roast marshmallow/}).click();await expect.poll(async()=>Number(await page.locator(".world-canvas").getAttribute("data-roasting-at"))).toBeGreaterThan(0);
 const seat=await second.locator(".world-canvas").getAttribute("data-seat-id");await second.reload();await expect(second.locator(".connection")).toHaveText("Connected");await expect(second.locator(".world-canvas")).toHaveAttribute("data-seat-id",seat!);
 await second.evaluate(()=>{Object.defineProperty(document,"hidden",{configurable:true,get:()=>true});document.dispatchEvent(new Event("visibilitychange"));});await second.waitForTimeout(300);const frame=await second.locator(".world-canvas").getAttribute("data-render-frame");await second.waitForTimeout(500);expect(await second.locator(".world-canvas").getAttribute("data-render-frame")).toBe(frame);await second.evaluate(()=>{delete(document as unknown as Record<string,unknown>).hidden;document.dispatchEvent(new Event("visibilitychange"));});await expect.poll(()=>second.locator(".world-canvas").getAttribute("data-render-frame")).not.toBe(frame);
 await page.screenshot({path:"tests/e2e/artifacts/campsite-current.png",fullPage:true});expect(errors).toEqual([]);
 }finally{await context.close();}
});
async function walk(page:Page,x:number,y:number){const world=page.locator('.world-canvas');const screen=await world.evaluate((el,p)=>{const d=(el as HTMLElement).dataset,b=el.querySelector('canvas')!.getBoundingClientRect();return{x:b.x+(p.x*32-Number(d.cameraScrollX))*Number(d.cameraZoom),y:b.y+(p.y*32-Number(d.cameraScrollY))*Number(d.cameraZoom)}},{x,y});await page.mouse.click(screen.x,screen.y);await expect.poll(async()=>{const d=await world.evaluate(el=>(el as HTMLElement).dataset);return Math.hypot(Number(d.authoritativeX)-x,Number(d.authoritativeY)-y)},{timeout:10000}).toBeLessThan(.5);}
test('physical bulletin board opens notes; walking to cabin confirms race and return restores camp',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await create(page);await expect(page.locator('.world-canvas')).toHaveAttribute('data-seat-id',/camp-seat-/);
 await walk(page,24,20);const board=await page.locator('.world-canvas').evaluate(el=>{const d=(el as HTMLElement).dataset,b=el.querySelector('canvas')!.getBoundingClientRect();return{x:b.x+(21.25*32-Number(d.cameraScrollX))*Number(d.cameraZoom),y:b.y+(19*32-Number(d.cameraScrollY))*Number(d.cameraZoom)}});await page.mouse.click(board.x,board.y);await expect(page.getByRole('heading',{name:'The idea board.'})).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
 await walk(page,24,16);await walk(page,18.5,16);
 const door=await page.locator('.world-canvas').evaluate(el=>{const d=(el as HTMLElement).dataset,b=el.querySelector('canvas')!.getBoundingClientRect();return{x:b.x+(15*32-Number(d.cameraScrollX))*Number(d.cameraZoom),y:b.y+(14.5*32-Number(d.cameraScrollY))*Number(d.cameraZoom)}});await page.mouse.click(door.x,door.y);await expect(page.getByRole('heading',{name:'Join the race?'})).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('.world-canvas')).toHaveAttribute('data-mode','home');await page.waitForTimeout(500);await expect(page.getByRole('heading',{name:'Join the race?'})).toHaveCount(0);await page.keyboard.press('e');await expect(page.getByRole('heading',{name:'Join the race?'})).toBeVisible();await page.getByRole('button',{name:'Join race',exact:true}).click();await expect(page.locator('.world-canvas')).toHaveAttribute('data-mode','race');await expect(page.getByRole('region',{name:'Race waiting lobby'})).toBeVisible();await page.getByRole('button',{name:'Ready to race',exact:true}).click();await expect(page.getByRole('region',{name:'Race waiting lobby'})).toHaveCount(0);await expect(page.locator('.race-status')).toContainText(/\d+\.\d+s/,{timeout:6000});await page.locator('.world-canvas').focus();const before=Number(await page.locator('.world-canvas').getAttribute('data-authoritative-y'));await page.keyboard.down('Space');await page.waitForTimeout(180);await page.keyboard.up('Space');await expect.poll(async()=>Number(await page.locator('.world-canvas').getAttribute('data-authoritative-y'))).toBeLessThan(before-.3);
 await page.getByRole('button',{name:/Return/}).first().click();await expect(page.locator('.world-canvas')).toHaveAttribute('data-mode','home');await expect(page.locator('.world-canvas')).toHaveAttribute('data-world-id','forest');expect(errors).toEqual([]);
});

test("friends join the same waiting lobby and ready together before synchronized countdown",async({browser,page})=>{
 test.setTimeout(120000);const context=await browser.newContext(),friend=await context.newPage();
 async function enter(p:Page){await walk(p,24,16);await walk(p,18.5,16);const q=await p.locator('.world-canvas').evaluate(el=>{const d=(el as HTMLElement).dataset,b=el.querySelector('canvas')!.getBoundingClientRect();return{x:b.x+(15*32-Number(d.cameraScrollX))*Number(d.cameraZoom),y:b.y+(14.5*32-Number(d.cameraScrollY))*Number(d.cameraZoom)}});await p.mouse.click(q.x,q.y);await expect(p.getByRole('heading',{name:'Join the race?'})).toBeVisible();await p.getByRole('button',{name:'Join race',exact:true}).click();await expect(p.getByRole('region',{name:'Race waiting lobby'})).toBeVisible();}
 try{const id=await create(page);await join(friend,id);await enter(page);const position=await page.locator('.world-canvas').getAttribute('data-authoritative-x');await page.waitForTimeout(3300);expect(await page.locator('.world-canvas').getAttribute('data-authoritative-x')).toBe(position);await expect(friend.locator('.world-canvas')).toHaveAttribute('data-mode','home');await enter(friend);await expect(page.getByRole('region',{name:'Race waiting lobby'})).toContainText('Remy');await page.getByRole('button',{name:'Ready to race',exact:true}).click();await page.waitForTimeout(700);await expect(page.getByRole('region',{name:'Race waiting lobby'})).toBeVisible();await friend.getByRole('button',{name:'Ready to race',exact:true}).click();await Promise.all([page,friend].map(async p=>{await expect(p.getByRole('region',{name:'Race waiting lobby'})).toHaveCount(0);await expect(p.locator('.countdown')).toBeVisible();}));await Promise.all([page,friend].map(p=>expect(p.locator('.race-status')).toContainText(/\d+\.\d+s/,{timeout:6000})));await page.screenshot({path:'tests/e2e/artifacts/shared-race-lobby.png'});}
 finally{await context.close();}
});
