import type { Point } from './index';

export type ForestNpcRole='wizard'|'queen'|'king'|'guard'|'watch'|'cat'|'witch'|'warlock'|'cheesemonger'|'peasant'|'innkeeper'|'knight'|'flirt'|'ogre'|'goblin';
export type ForestStoryState='first-meeting'|'ward-search'|'wards-restored'|'keeper-found';
export interface NpcAppearance {skin:string;hair:string;coat:string;trim:string}
export interface AuthoredForestNpc {
  id:string; name:string; role:ForestNpcRole; home:Point; appearance:NpcAppearance;
  backstory:string; motivation:string; relationships:readonly {npcId:string;bond:string}[];
  questHooks:readonly string[];
  ambientLines:readonly string[];
  routine:{day:readonly Point[];dusk:readonly Point[];night:readonly Point[]};
  dialogue:Readonly<Record<ForestStoryState,string>>;
}
const palette={
  wizard:{skin:'#c58d69',hair:'#ccc1a5',coat:'#56648d',trim:'#d7b766'},
  royal:{skin:'#a96946',hair:'#3e2929',coat:'#77546d',trim:'#e2bc61'},
  guard:{skin:'#d7ac89',hair:'#594234',coat:'#75868b',trim:'#d0b97d'},
  meadow:{skin:'#d9b08b',hair:'#774431',coat:'#6b8660',trim:'#d8c49a'},
  witch:{skin:'#b77e61',hair:'#cab78b',coat:'#546c64',trim:'#b1a1bf'},
  cat:{skin:'#b07a48',hair:'#6b493c',coat:'#527c87',trim:'#edc791'},
  warlock:{skin:'#9c877c',hair:'#332e41',coat:'#494961',trim:'#a1b5ac'},
  goblin:{skin:'#839c5b',hair:'#4e593c',coat:'#936d4d',trim:'#cdbb77'},
  ogre:{skin:'#879879',hair:'#455846',coat:'#8d7058',trim:'#d4c6a0'},
} satisfies Record<string,NpcAppearance>;
const ambient:Readonly<Record<string,readonly string[]>>={
  'wizard-orin-vale':['Tansy says a kettle is a practical star. I have stopped arguing; the tea is excellent.','If you discover anything odd, describe it before you name it. Names can hide the interesting part.'],
  'queen-elowen':['The crown is borrowed. The responsibility, unfortunately, fits perfectly.','Iona brings me the reports I need, including the ones I would rather not read.'],
  'king-rowan':['Brindle can lift the gate with one hand. I try not to make that our entire maintenance plan.','A good orchard has room for crooked trees. A good court might learn something from that.'],
  'guard-iona':['Garrick writes his reports on flour sacks. They are the most useful reading in the castle.','A patrol is a promise to come back past the same people and check they are still all right.'],
  'watch-garrick':['If Juniper calls a delivery urgent, ask whether the fishmonger closes early.','Walk where you can hear your own footsteps. It is easier to notice an extra pair.'],
  'cat-juniper':['I accept payment in coins, bread, or a convincing apology for waking me.','Merrit says his cheese is not for cats. I have requested that in writing.'],
  'witch-tansy-reed':['People ask whether the herbs are enchanted. Watering them regularly is sufficiently miraculous.','Some things need a spell. Most things need a chair and someone who listens.'],
  'warlock-vesper':['The stars have never asked me to explain myself. I may have leaned on that advantage too heavily.','Do not mistake a quiet wood for an empty one. Listening is a kind of company.'],
  'cheesemonger-merrit':['I label the samples. Juniper calls that a menu. We are still negotiating.','A rind is not a wall. Leave something for whoever arrives after you.'],
  'innkeeper-nessa':['Sit, if you like. You do not have to explain why you are tired.','Fenn can compose a sonnet in a minute and postpone a washing-up for an hour. Remarkable talent.'],
  'peasant-pell':['Lark draws maps on my patterns. My best coat now includes a shortcut to the castle.','A neat patch is nothing to be ashamed of. It means something was worth keeping.'],
  'peasant-lark':['Ser Calder asks for directions and then actually follows them. I like that in a knight.','If a path changes, change the map. Being right yesterday does not get you home tonight.'],
  'knight-ser-calder':['Brindle wins our practice bouts. I win the argument about who brings the biscuits.','You can lower your shoulders here. I shall look stern enough for both of us.'],
  'flirt-fenn':['My tragic flaw is that I am very available to avoid doing the dishes.','Juniper charges by the verse. Romance has become an unexpectedly precise expense.'],
  'ogre-brindle':['Basil likes a little water. I like a lot of soup. Neither of us is complicated.','The king helps with my garden. Very small shovel. Very serious king.'],
  'goblin-pip':['A recipe is a story with stricter measurements. Nib is not allowed to write the recipes.','Merrit saves the crunchy bits for us. Good neighbours understand crunchy bits.'],
  'goblin-tulla':['Pip borrowed six spoons. He returned seven. This is not the comforting result he thinks it is.','An honest receipt is small magic. It makes two people remember the same thing.'],
  'goblin-nib':['Brindle says I am brave. Tulla says I am late with the washing. Both may be true.','Would you like the short version or the version with the dragon? Tulla says short.'],
};
function resident(input:Omit<AuthoredForestNpc,'routine'|'ambientLines'>&{route?:readonly Point[];night?:readonly Point[]}):AuthoredForestNpc {
  const {route,night,...rest}=input;
  const day=route??[input.home,{x:input.home.x+1,y:input.home.y}];
  return {...rest,ambientLines:ambient[input.id]??[],routine:{day,dusk:[...day].reverse(),night:night??[input.home]}};
}

/** Fixed outdoor routines are deliberately short. Actors never wander across the
 * whole map to find a random goal; schedules change intentions, not ownership. */
export const AUTHORED_FOREST_NPCS:readonly AuthoredForestNpc[]=[
  resident({id:'wizard-orin-vale',name:'Orin Vale',role:'wizard',home:{x:46,y:85},appearance:palette.wizard,
    backstory:'Ada taught the royal astronomer to read a forest instead of a sky. He left court to become her apprentice.',motivation:'Repair the three brass wards and find Ada without sending another friend into the dark.',
    relationships:[{npcId:'witch-tansy-reed',bond:'Old collaborator; her practical magic steadies his theories.'},{npcId:'queen-elowen',bond:'Former adviser who still owes the queen an honest answer.'}],questHooks:['forest-ward-seals','keeper-trail'],route:[{x:44,y:84},{x:48,y:84},{x:48,y:87},{x:44,y:87}],
    dialogue:{'first-meeting':'Ada, our keeper, is missing. Three stolen brass wards still know the path she took. Will you help?','ward-search':'The Button goblins have the seals. Ask before you swing; fear makes a poor translator.','wards-restored':'The wards hum toward Hollow Bough. Ada left a journal in her unlatched house to the southwest.','keeper-found':'A forest is kept by all who care for it. Ada knew. I needed rather more evidence.'}}),
  resident({id:'queen-elowen',name:'Queen Elowen',role:'queen',home:{x:121,y:23},appearance:palette.royal,
    backstory:'Elected queen after the old court fled a flood, Elowen wears a borrowed crown and remembers every family who stayed.',motivation:'Keep the village safe without pretending the court understands the threat.',relationships:[{npcId:'king-rowan',bond:'Partner in life; argues gently with his faith in ceremonies.'},{npcId:'guard-iona',bond:'Trusts Iona to question royal orders.'}],questHooks:['court-of-small-promises','keeper-trail'],route:[{x:120,y:23},{x:123,y:23},{x:123,y:25},{x:120,y:25}],
    dialogue:{'first-meeting':'Ada refused a title. She said the trees would not know what to call her. Bring her home.','ward-search':'Iona saw the keeper pass without her lantern. Ada never went anywhere without that lantern.','wards-restored':'A familiar face is not proof. Ask what kindness it remembers; Ada always remembered yours.','keeper-found':'The crown can wait. There is an extra chair at supper, and it has its owner again.'}}),
  resident({id:'king-rowan',name:'King Rowan',role:'king',home:{x:129,y:24},appearance:{...palette.royal,coat:'#4e7580',hair:'#baaa7e'},
    backstory:'A former orchard keeper chosen as consort, Rowan repairs gates more comfortably than he gives speeches.',motivation:'Make Crownwatch useful, not impressive.',relationships:[{npcId:'queen-elowen',bond:'Married to the person beneath the borrowed crown.'},{npcId:'ogre-brindle',bond:'Brindle once held a floodgate while Rowan rebuilt it.'}],questHooks:['royal-repairs','court-of-small-promises'],route:[{x:128,y:23},{x:130,y:23},{x:130,y:25},{x:128,y:25}],
    dialogue:{'first-meeting':'I am told kings should have grand plans. Mine is hinges. No one sleeps well behind a broken gate.','ward-search':'Brindle saw someone wearing Ada’s face refuse a shared meal. That bothered him more than the claws.','wards-restored':'The north bell rings true again. Good. We shall have music while we mend the south gate.','keeper-found':'A small kingdom, a long table, everybody accounted for. That is all the grandeur I need.'}}),
  resident({id:'guard-iona',name:'Iona · castle guard',role:'guard',home:{x:116,y:24},appearance:palette.guard,
    backstory:'Iona joined the guard after Ada found her lost in a snowstorm. She now records the weather beside every patrol report.',motivation:'Learn why a perfect copy of Ada left no breath in the cold.',relationships:[{npcId:'watch-garrick',bond:'Former patrol partner; trusts his village gossip as evidence.'},{npcId:'queen-elowen',bond:'Protects the court by telling the truth to it.'}],questHooks:['unwritten-patrol','keeper-trail'],route:[{x:115,y:23},{x:115,y:26},{x:134,y:26},{x:134,y:22},{x:115,y:22}],night:[{x:119,y:22},{x:130,y:22}],
    dialogue:{'first-meeting':'Castle watch. I record faces, voices and footprints. Lately the first two have become unreliable.','ward-search':'My report says “Ada, eastbound.” My margin says “no breath in the cold.” Read the margin.','wards-restored':'The ward caught its shadow moving a heartbeat late. Tell Orin. Details beat bravery.','keeper-found':'New patrol rule: nobody walks home alone. Even guards are allowed good company.'}}),
  resident({id:'watch-garrick',name:'Garrick · town watch',role:'watch',home:{x:97,y:40},appearance:{...palette.guard,coat:'#7c6851',skin:'#936548'},
    backstory:'Once a miller, Garrick became the watch after noticing everyone told him their troubles while waiting for flour.',motivation:'Keep the roads open and stop frightened villagers accusing one another.',relationships:[{npcId:'guard-iona',bond:'Exchanges signed reports with the castle guard.'},{npcId:'cat-juniper',bond:'Pays his best courier in warm bread.'}],questHooks:['unwritten-patrol','courier-round'],route:[{x:97,y:28},{x:99,y:28},{x:99,y:50},{x:97,y:50}],night:[{x:97,y:35},{x:97,y:43}],
    dialogue:{'first-meeting':'Bramblewick watch. If you have lost a person, tell me. If you have lost a hat, tell Juniper.','ward-search':'No witch hunts here. Tansy has mended more broken people than half this town has met.','wards-restored':'The roads sound like roads again. I still walk them twice; relief is not a patrol.','keeper-found':'One fewer missing-person notice. That is a very good morning’s work.'}}),
  resident({id:'cat-juniper',name:'Juniper Claw',role:'cat',home:{x:100,y:40},appearance:palette.cat,
    backstory:'A talking cat who insisted on standing upright to carry more letters, Juniper remembers every doorstep and no appointment.',motivation:'Deliver Ada’s final letter without admitting she put it under a fish invoice.',relationships:[{npcId:'watch-garrick',bond:'Employer and reliable source of bread.'},{npcId:'cheesemonger-merrit',bond:'A commercial rivalry over unattended dairy.'}],questHooks:['courier-round','keeper-trail'],route:[{x:100,y:38},{x:104,y:38},{x:104,y:40},{x:100,y:40}],
    dialogue:{'first-meeting':'Yes, I am a cat. Yes, I deliver letters. No, scratching at your door does not make it less official.','ward-search':'Ada’s letter says “the face follows, the name stays.” It was under an invoice. Entirely secure.','wards-restored':'I delivered your news to the queen. She tipped me a ribbon. Clearly a woman of culture.','keeper-found':'Ada scratched behind my ears and then thanked me. Correct order. A professional understands.'}}),
  resident({id:'witch-tansy-reed',name:'Tansy Reed',role:'witch',home:{x:108,y:71},appearance:palette.witch,
    backstory:'The reed witch learned medicine from her grandmother and magic by arguing with the rain until it listened.',motivation:'Reconcile Orin and Vesper before their pride makes the missing keeper harder to find.',relationships:[{npcId:'wizard-orin-vale',bond:'Keeps his extravagant theories tethered to ordinary life.'},{npcId:'warlock-vesper',bond:'Her estranged brother, whose warnings she still believes.'}],questHooks:['reed-and-ash','keeper-trail'],route:[{x:105,y:70},{x:110,y:70},{x:110,y:73},{x:105,y:73}],
    dialogue:{'first-meeting':'Tea first, omens second. Fear makes people wonderfully certain and very poor listeners.','ward-search':'My brother Vesper did not steal those wards. He warned us what would come when they fell silent.','wards-restored':'Take the journal to Hollow Bough. Tell Vesper I kept his cup, if he asks. He will not ask.','keeper-found':'Two cups washed, one friend home. The grandest magic usually looks like housework.'}}),
  resident({id:'warlock-vesper',name:'Vesper Ash',role:'warlock',home:{x:124,y:94},appearance:palette.warlock,
    backstory:'Vesper tried to catalogue the forest’s echoes. One answered in his voice, and the court called his warning a threat.',motivation:'Undo the invitation he accidentally gave the mimics and earn Tansy’s trust again.',relationships:[{npcId:'witch-tansy-reed',bond:'His sister kept a place for him even when he stopped visiting.'},{npcId:'wizard-orin-vale',bond:'A scientific rival who mistook shame for secrecy.'}],questHooks:['reed-and-ash','keeper-trail'],route:[{x:121,y:94},{x:127,y:94},{x:127,y:97},{x:121,y:97}],
    dialogue:{'first-meeting':'A warlock lives in the dead woods. An easy story. The truth is that I stayed when they died.','ward-search':'The goblins were paid in borrowed voices. They thought the keeper herself had made the bargain.','wards-restored':'Ada followed the echo under the old roots. Her journal names the kindness it cannot copy.','keeper-found':'Tansy kept my cup? Ah. I have been rehearsing an apology far more difficult than that walk.'}}),
  resident({id:'cheesemonger-merrit',name:'Merrit Rind',role:'cheesemonger',home:{x:106,y:39},appearance:{...palette.meadow,coat:'#d1ac66',hair:'#554437'},
    backstory:'Merrit inherited a cheese shop and an unreasonable number of accounting ledgers, then discovered that everybody talks at tasting time.',motivation:'Recover the stolen supply cart and feed both sides before a quarrel becomes a war.',relationships:[{npcId:'goblin-pip',bond:'Pip buys rind scraps honestly whenever fear allows.'},{npcId:'cat-juniper',bond:'Pretends not to notice the occasional missing sample.'}],questHooks:['a-fair-rind','forest-ward-seals'],route:[{x:105,y:38},{x:107,y:38},{x:107,y:41},{x:105,y:41}],
    dialogue:{'first-meeting':'Cheese is a conversation that takes several weeks. Try the sharp one; it has something to say.','ward-search':'Pip paid for the cheese. Whoever ordered the stolen cart paid in my voice. I was here all night.','wards-restored':'Bring the goblins to the table. I can replace a cart; I cannot replace a good neighbour.','keeper-found':'The keeper’s homecoming wheel is ready. Nobody tell Juniper where I put it.'}}),
  resident({id:'innkeeper-nessa',name:'Nessa Hearth',role:'innkeeper',home:{x:92,y:39},appearance:{...palette.meadow,coat:'#a86d62',hair:'#302a28',skin:'#90664c'},
    backstory:'Nessa rebuilt the inn after the flood with timber Ada marked safe. The spare chair is a debt made comfortable.',motivation:'Make sure every frightened traveller has somewhere ordinary to sit.',relationships:[{npcId:'peasant-pell',bond:'Keeps a bowl aside when the mender works late.'},{npcId:'flirt-fenn',bond:'Employs Fenn and sees through every elaborate excuse.'}],questHooks:['the-extra-chair','keeper-trail'],route:[{x:90,y:38},{x:94,y:38},{x:94,y:40},{x:90,y:40}],
    dialogue:{'first-meeting':'Warm bowls, dry socks, extra chair. You need not be on a quest to deserve any of them.','ward-search':'Ada always left the last apple for someone else. The copy asked for every apple in the room.','wards-restored':'Good news travels faster when you carry it to a table. Stay as long as you like.','keeper-found':'Her chair was never empty. It was waiting. There is a difference.'}}),
  resident({id:'peasant-pell',name:'Pell Morrow',role:'peasant',home:{x:91,y:51},appearance:palette.meadow,
    backstory:'A tenant farmer turned mender after the river took his field, Pell can identify his stitching in the dark.',motivation:'Find out why Ada’s abandoned cloak has no mud inside the hem.',relationships:[{npcId:'peasant-lark',bond:'Daughter and better map-reader than he will admit.'},{npcId:'innkeeper-nessa',bond:'An old friend who trades dinner for repairs.'}],questHooks:['the-mended-hem','keeper-trail'],route:[{x:90,y:51},{x:94,y:51},{x:94,y:53},{x:90,y:53}],
    dialogue:{'first-meeting':'A torn sleeve tells you what happened. A clean sleeve sometimes tells you rather more.','ward-search':'That cloak looked like Ada’s, but I mend from the inside. Whoever copied it only saw the outside.','wards-restored':'Lark found the real hem snagged on the keeper’s gate. Follow a repair; it remembers the wearer.','keeper-found':'I shall put a bright patch on her coat. No charge. I simply want to see her coming.'}}),
  resident({id:'peasant-lark',name:'Lark Morrow',role:'peasant',home:{x:97,y:53},appearance:{...palette.meadow,coat:'#6f93a1',hair:'#392f28'},
    backstory:'Lark charts footpaths in the margins of her father’s sewing patterns. Ada was the first adult who called them maps.',motivation:'Prove that careful observation matters more than a title or a sword.',relationships:[{npcId:'peasant-pell',bond:'Father, teacher and reluctant first reader.'},{npcId:'knight-ser-calder',bond:'Calder takes her directions without talking down to her.'}],questHooks:['the-mended-hem','unwritten-patrol'],route:[{x:96,y:52},{x:98,y:52},{x:98,y:54},{x:96,y:54}],
    dialogue:{'first-meeting':'This is a map, not a doodle. Doodles do not usually help you get home.','ward-search':'Two sets of Ada’s prints. One avoids every puddle; one walks through them. She loved the sound.','wards-restored':'I marked the real trail toward the unlatched house. Please bring my map back with more on it.','keeper-found':'Ada asked for a copy of my map. I think that makes me a mapmaker. I think I already was.'}}),
  resident({id:'knight-ser-calder',name:'Ser Calder',role:'knight',home:{x:112,y:26},appearance:{...palette.guard,trim:'#a8c8bb',skin:'#b47c58'},
    backstory:'A wandering knight who lost a tournament by stopping to help a fallen rival, Calder decided he preferred the help.',motivation:'Protect the road without treating every unfamiliar creature as an enemy.',relationships:[{npcId:'peasant-lark',bond:'Trusts her maps more than his heroic instincts.'},{npcId:'ogre-brindle',bond:'Sparring partner; both favour the picnic afterwards.'}],questHooks:['a-quiet-kind-of-brave','unwritten-patrol'],route:[{x:110,y:24},{x:113,y:24},{x:113,y:28},{x:110,y:28}],
    dialogue:{'first-meeting':'A knight ought to know when to draw a blade. More useful still: knowing when to put it away.','ward-search':'The goblins look frightened, not triumphant. That distinction has saved me several apologies.','wards-restored':'I will keep the road behind you clear. A retreat is a route someone was wise enough to prepare.','keeper-found':'They want a song about the rescue. Give everyone a verse, especially the ones who made tea.'}}),
  resident({id:'flirt-fenn',name:'Fenn Foxglove',role:'flirt',home:{x:100,y:44},appearance:{...palette.meadow,coat:'#ad718c',hair:'#5d392e'},
    backstory:'Fenn writes glorious love letters for other people and disappointingly vague messages for himself.',motivation:'Do one useful thing without first checking who is watching.',relationships:[{npcId:'innkeeper-nessa',bond:'His employer keeps him honest and occasionally busy.'},{npcId:'cat-juniper',bond:'Juniper charges extra for delivering poetry.'}],questHooks:['a-letter-without-a-mirror','courier-round'],route:[{x:100,y:44},{x:102,y:44},{x:102,y:46},{x:100,y:46}],
    dialogue:{'first-meeting':'Were you looking for adventure, or did my entrance simply give that impression? Nessa says I owe her dishes.','ward-search':'Something copied my best greeting. Extremely flattering until it forgot the person it was greeting.','wards-restored':'I carried supplies without writing a poem about it. A bewildering amount got done.','keeper-found':'My new letter starts with “How are you?” Apparently that is an improvement.'}}),
  resident({id:'ogre-brindle',name:'Brindle',role:'ogre',home:{x:55,y:86},appearance:palette.ogre,
    backstory:'Brindle once held a floodgate shut for an entire night. He now grows tiny herbs in enormous boots.',motivation:'Keep the small things safe and recover the kettle the goblins borrowed.',relationships:[{npcId:'king-rowan',bond:'Friends since the flood, regardless of crowns.'},{npcId:'goblin-pip',bond:'Lends kitchen equipment and pretends not to count it.'}],questHooks:['the-smallest-garden','a-fair-rind'],route:[{x:53,y:85},{x:58,y:85},{x:58,y:88},{x:53,y:88}],
    dialogue:{'first-meeting':'Careful of the boot. Basil lives there. I live here. We manage.','ward-search':'Ada shares soup. The other Ada wanted me to put the fire out. I did not like that Ada.','wards-restored':'The kettle came back with flowers in it. Goblins apologise sideways, but it still counts.','keeper-found':'I made eight bowls. Then more bowls. Small happiness gets bigger when there is room for it.'}}),
  resident({id:'goblin-pip',name:'Pip Copperbutton',role:'goblin',home:{x:72,y:95},appearance:palette.goblin,
    backstory:'Pip became camp cook because he was the only goblin who could count spoons while hungry.',motivation:'Return what was borrowed and persuade the others they were tricked, not cursed.',relationships:[{npcId:'goblin-tulla',bond:'Sister and rigorous keeper of the camp inventory.'},{npcId:'cheesemonger-merrit',bond:'His favourite honest trader.'}],questHooks:['forest-ward-seals','a-fair-rind'],route:[{x:71,y:94},{x:75,y:94},{x:75,y:96},{x:71,y:96}],
    dialogue:{'first-meeting':'We borrowed the shiny thing. The keeper asked! Same face, same voice. Slightly too many elbows.','ward-search':'The brass seal is by the soup tent. Take it. Soup should not whisper back.','wards-restored':'No more whisper soup. We are celebrating with ordinary, suspiciously quiet soup.','keeper-found':'Real Ada called me Pip, not “small green one.” I like being Pip.'}}),
  resident({id:'goblin-tulla',name:'Tulla Mossbutton',role:'goblin',home:{x:84,y:85},appearance:{...palette.goblin,coat:'#597864',trim:'#bbc899'},
    backstory:'Tulla records every trade on bark strips and keeps the bark sorted by how worried she was when she wrote it.',motivation:'Learn why the keeper’s signature changed halfway through their bargain.',relationships:[{npcId:'goblin-pip',bond:'Brother who has misplaced every spoon exactly once.'},{npcId:'goblin-nib',bond:'Protects Nib from his own dramatic conclusions.'}],questHooks:['forest-ward-seals','the-bark-ledger'],route:[{x:82,y:84},{x:86,y:84},{x:86,y:86},{x:82,y:86}],
    dialogue:{'first-meeting':'A proper bargain has two names. This one had one name written twice, in different hands.','ward-search':'Seal by the north tent. Receipt stays with me. Evidence does not grow on—well, this evidence does.','wards-restored':'I filed the bargain under “voices are not signatures.” A growing section, unfortunately.','keeper-found':'Ada signed her own name this time. I gave her a receipt. She laughed like a person.'}}),
  resident({id:'goblin-nib',name:'Nib Pearlbutton',role:'goblin',home:{x:87,y:103},appearance:{...palette.goblin,coat:'#8f7184',trim:'#d3c5b8'},
    backstory:'Nib tells epic campfire stories in which he is usually a very tall goblin. He is learning shorter, truer versions.',motivation:'Admit he followed the wrong keeper and help undo the mistake.',relationships:[{npcId:'goblin-tulla',bond:'Tulla edits his stories into useful reports.'},{npcId:'ogre-brindle',bond:'Hero and preferred audience.'}],questHooks:['forest-ward-seals','the-bark-ledger'],route:[{x:84,y:103},{x:89,y:103},{x:89,y:105},{x:84,y:105}],
    dialogue:{'first-meeting':'I fought the shadow! In the sense that I shouted, and in the sense that it had already left.','ward-search':'Last seal by my tent. I kept it safe. Apart from the borrowing. And the board game.','wards-restored':'Here is the short story: I was scared. You helped. I can tell that one without making it bigger.','keeper-found':'Brindle said being honest was brave. I am putting that in the long version.'}}),
];

export interface ForestWildlife {id:string;kind:'rabbit'|'deer'|'fox'|'owl';name:string;home:Point;route:readonly Point[];speed:number;active:'day'|'night'|'always'}
export const FOREST_WILDLIFE:readonly ForestWildlife[]=[
  {id:'animal:orchard-rabbit',kind:'rabbit',name:'Orchard rabbit',home:{x:50,y:89},route:[{x:49,y:89},{x:51,y:89},{x:51,y:91},{x:49,y:91}],speed:.8,active:'day'},
  {id:'animal:reed-deer',kind:'deer',name:'Reed deer',home:{x:113,y:72},route:[{x:112,y:71},{x:115,y:73},{x:112,y:74}],speed:.9,active:'day'},
  {id:'animal:button-fox',kind:'fox',name:'Copper fox',home:{x:78,y:95},route:[{x:77,y:94},{x:80,y:96},{x:77,y:97}],speed:1.15,active:'always'},
  {id:'animal:hollow-owl',kind:'owl',name:'Hollow owl',home:{x:129,y:97},route:[{x:128,y:96},{x:130,y:96},{x:130,y:98},{x:128,y:98}],speed:.65,active:'night'},
];
export interface ForestStoryHook {id:string;title:string;from:string;to:readonly string[];premise:string;reveals:string;prerequisite?:string;scope:'personal'}
/** Narrative graph is authoring data. A hook here is not an automatically granted
 * quest or reward: integrate each executable objective with the durable journal. */
export const FOREST_STORY_HOOKS:readonly ForestStoryHook[]=[
  {id:'forest-ward-seals',title:'The Borrowed Light',from:'wizard-orin-vale',to:['goblin-pip','goblin-tulla','goblin-nib'],premise:'Recover three brass wards the goblins accepted from a copy of the keeper.',reveals:'A mimic borrowed familiar voices to silence the forest wards.',scope:'personal'},
  {id:'keeper-trail',title:'A Kindness It Cannot Copy',from:'wizard-orin-vale',to:['queen-elowen','witch-tansy-reed','warlock-vesper'],premise:'Read Ada’s journal, compare witness accounts and follow the real keeper’s trail.',reveals:'Memories of shared kindness distinguish Ada from an imitation.',prerequisite:'forest-ward-seals',scope:'personal'},
  {id:'unwritten-patrol',title:'Read the Margin',from:'guard-iona',to:['watch-garrick','peasant-lark','knight-ser-calder'],premise:'Compare castle and village patrol notes where the official report stops.',reveals:'The imitation casts a delayed shadow and leaves no breath in cold air.',scope:'personal'},
  {id:'court-of-small-promises',title:'A Borrowed Crown',from:'queen-elowen',to:['king-rowan','innkeeper-nessa'],premise:'Carry the court’s promise of an open table to the people who rebuilt it.',reveals:'The royal family serves by consent; the village’s trust keeps Crownwatch standing.',scope:'personal'},
  {id:'royal-repairs',title:'The King’s Hinges',from:'king-rowan',to:['ogre-brindle'],premise:'Find the floodgate builder who understands the castle’s stubborn gate.',reveals:'Rowan and Brindle saved the town together before anyone wore a crown.',scope:'personal'},
  {id:'courier-round',title:'Under the Fish Invoice',from:'cat-juniper',to:['watch-garrick','flirt-fenn'],premise:'Help Juniper sort a misfiled letter and deliver it to the right doorstep.',reveals:'Ada warned that a stolen name cannot steal the promises attached to it.',scope:'personal'},
  {id:'reed-and-ash',title:'The Kept Cup',from:'witch-tansy-reed',to:['warlock-vesper'],premise:'Carry a small peace offering between two estranged siblings.',reveals:'Vesper’s failed experiment invited the echoes; shame kept him from asking for help.',prerequisite:'forest-ward-seals',scope:'personal'},
  {id:'a-fair-rind',title:'Neighbours, Not Thieves',from:'cheesemonger-merrit',to:['goblin-pip','ogre-brindle'],premise:'Reconcile a frightened goblin cook and a tradesman impersonated by the mimic.',reveals:'The stolen cart was ordered in Merrit’s own borrowed voice.',scope:'personal'},
  {id:'the-extra-chair',title:'An Ordinary Welcome',from:'innkeeper-nessa',to:['peasant-pell'],premise:'Set a place and mend a blanket for someone who arrives with nothing.',reveals:'Keeping the forest begins with keeping one another.',scope:'personal'},
  {id:'the-mended-hem',title:'Inside the Stitch',from:'peasant-pell',to:['peasant-lark'],premise:'Compare the inside of Ada’s cloak with the imitation left behind.',reveals:'The mimic copies what it sees, but misses hidden repairs and lived histories.',scope:'personal'},
  {id:'a-quiet-kind-of-brave',title:'The Sword Stays Sheathed',from:'knight-ser-calder',to:['ogre-brindle','peasant-lark'],premise:'Walk a safe route and let the people who know it lead.',reveals:'Protection is making room for others to return, not collecting defeated enemies.',scope:'personal'},
  {id:'a-letter-without-a-mirror',title:'How Are You?',from:'flirt-fenn',to:['cat-juniper','innkeeper-nessa'],premise:'Help Fenn write one sincere sentence and finish the work he promised.',reveals:'Attention becomes affection when it notices another person.',scope:'personal'},
  {id:'the-smallest-garden',title:'Basil’s Boot',from:'ogre-brindle',to:['king-rowan','goblin-pip'],premise:'Find Brindle’s borrowed kettle without trampling his very small garden.',reveals:'The largest hands in the forest are careful with the smallest things.',scope:'personal'},
  {id:'the-bark-ledger',title:'Two Hands, One Name',from:'goblin-tulla',to:['goblin-nib','wizard-orin-vale'],premise:'Compare a strange signature with Nib’s less embellished account.',reveals:'The same voice made promises in two incompatible hands.',scope:'personal'},
];
export function forestNpcDialogue(npc:AuthoredForestNpc,flags:{wardAccepted?:boolean;wardsRestored?:boolean;keeperFound?:boolean}):string {
  return npc.dialogue[flags.keeperFound?'keeper-found':flags.wardsRestored?'wards-restored':flags.wardAccepted?'ward-search':'first-meeting'];
}
export function forestNpcRoute(npc:AuthoredForestNpc,phase:'dawn'|'day'|'dusk'|'night'):readonly Point[]{return npc.routine[phase==='dawn'?'day':phase];}
