"use client";
import {useEffect,useRef,useState} from 'react';
import {usePanelGameFocus} from '../lib/use-panel-game-focus';
import {getWorld,ASYLUM_DOOR} from '@third-space/config';
import {FOREST_INTERIORS,FOREST_ROADS,FOREST_BUILDINGS} from '../../../packages/config/src/authored-forest';
import type {Snapshot} from '../lib/types';
export default function WorldMap({snapshot,selfId}:{snapshot:Snapshot|null;selfId:string}){
 const [open,setOpen]=useState(false),toggle=useRef<HTMLButtonElement>(null);
 usePanelGameFocus(open,".navigation-map",".navigation-map > button");
 useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!event.defaultPrevented&&document.activeElement?.closest(".navigation-map")){event.preventDefault();setOpen(false);}};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape);},[open]);
 if(!snapshot)return null;
 const self=snapshot.players.find(p=>p.id===selfId);if(!self||self.mode!=="home")return null;
 const world=getWorld(snapshot.worldId),map=world.map,members=snapshot.members??snapshot.players;
 const heading={up:'N',right:'E',down:'S',left:'W'}[self.facing];
 return <aside className="navigation-map" aria-label="World map"><button ref={toggle} type="button" aria-controls="world-map-card" aria-expanded={open} aria-label="Toggle map" onClick={()=>setOpen(previous=>!previous)}>⌖ {heading} · Map</button>{open&&<div id="world-map-card" className="map-card"><div className="map-heading"><strong>{world.name}</strong><button type="button" aria-label="Close map" onClick={()=>{setOpen(false);}}>×</button></div><svg viewBox={`0 0 ${map.width} ${map.height}`} role="img" aria-label="Map of friends, campfire and race cabin" preserveAspectRatio="xMidYMid meet"><rect width={map.width} height={map.height} fill="#152d26"/>{map.solids.map((s,i)=><rect key={i} x={s.x} y={s.y} width={s.width} height={s.height} fill="#405644"/>)}{snapshot.worldId==='forest'&&<>{FOREST_ROADS.map(road=><polyline key={road.id} points={road.points.map(p=>`${p.x},${p.y}`).join(' ')} stroke="#80785a" strokeWidth="1.4" fill="none"/>)}{FOREST_BUILDINGS.map(b=><rect key={b.id} x={b.footprint.x} y={b.footprint.y} width={b.footprint.width} height={b.footprint.height} fill="#b3a078"><title>{b.name}</title></rect>)}<text x={46} y={89} textAnchor="middle" fontSize={4} fill="#f0d692">Orin</text><text x={102} y={47} textAnchor="middle" fontSize={4} fill="#f0d692">Town board</text><path d="M24 24 H15 V14.5" stroke="#80785a" strokeWidth="1.7" fill="none"/><circle cx={24} cy={24} r={1.8} fill="#f4b66b"><title>Campfire / spawn</title></circle><rect x={12} y={9} width={6} height={5} fill="#9da6ad"><title>Race cabin — walk to the south door</title></rect></>}{snapshot.worldId==='asylum'&&<><circle cx={10} cy={10} r={.7} fill="#efb566"/><rect x={16} y={9} width={1} height={1} fill="#8fc7a7"><title>Instant flashlight charger</title></rect><rect x={9} y={18} width={2} height={.7} fill="#c6b78d"><title>Exit to forest</title></rect></>}{members.filter(p=>p.mode==='home'&&(snapshot.worldId==='forest'||p.zone===self.zone)).map(p=>{const position=snapshot.worldId==='forest'&&p.zone?(p.zone==='asylum'?ASYLUM_DOOR:FOREST_INTERIORS.find(i=>i.id===p.zone)?.returnPoint??p):p;return <circle key={p.id} cx={position.x} cy={position.y} r={p.id===selfId ? .85 : .6} fill={p.id===selfId?'#fff8da':p.zone?'#b19bcd':'#88d8c5'} stroke="#17271f" strokeWidth={.2}><title>{p.name}{p.zone?' · inside '+getWorld(p.zone).name:''}{p.id===selfId?' · you':''}</title></circle>;})}</svg><p>◉ You · ● Friends · 🔥 Camp · ▣ Race cabin</p><ul>{members.filter(p=>p.mode==='home').map(p=><li key={p.id}>{p.name} · {p.zone?getWorld(p.zone).name:'Outside'}{p.id===selfId?' (you)':''}</li>)}</ul></div>}</aside>;
}
