import { describe, expect, it } from 'vitest';
import { ForestMimic, MIMIC_TUNING as T } from '../../apps/game-server/src/ForestMimic';
import { getWorld, type WorldDefinition } from '../../packages/config/src/index';
import { FOREST_VIEW, outsideForestView, forestCameraZoom } from '../../packages/config/src/forest-view';
import { createPlayer, distance } from '../../packages/simulation/src/index';
const world: WorldDefinition = { ...getWorld('forest'), map: { ...getWorld('forest').map, solids: [], furniture: [
 {id:'tree',kind:'tree',footprint:{x:43,y:43,width:2,height:3},collider:null,usePoints:[],seats:[]},
] } };
function fixture(){ const mimic=new ForestMimic(world,()=>.5),p={...createPlayer('p','Player'),x:14,y:45};mimic.reset(1000);return {mimic,p}; }
function spawn(m:ForestMimic,p=fixture().p){m.update(121000,[p]);expect(m.state?.phase).toBe('approach');}
function linger(m:ForestMimic,p=fixture().p){spawn(m,p);p.x=m.state!.x-2;p.y=m.state!.y;m.update(121100,[p]);expect(m.state?.phase).toBe('linger');return p;}
function morph(m:ForestMimic,p=fixture().p){linger(m,p);m.update(123300,[p]);expect(m.state?.phase).toBe('morph');return p;}
describe('room-owned mimic',()=>{
 it('is rare and defers without exposed players or an unseen spawn',()=>{expect(T.intervalMs).toBe(120000);const {mimic,p}=fixture();mimic.update(120999,[p]);expect(mimic.state).toBeNull();p.x=24;p.y=24;mimic.update(121000,[p]);expect(mimic.state).toBeNull();});
 it('captures cosmetic player or NPC appearance without aliasing identity',()=>{const {mimic,p}=fixture();spawn(mimic,p);const color=mimic.state!.disguise.hairColor;p.avatar.hairColor='#000000';expect(mimic.state!.disguise.hairColor).toBe(color);expect(mimic.state!.disguisePlayerId).toBe(p.id);
 const second=fixture();const npc={...createPlayer('npc:test','Actor'),x:12,y:45};second.mimic.update(121000,[second.p,npc],[second.p]);expect(second.mimic.state!.disguisePlayerId).toBe(npc.id);
 });
 it('approaches calmly, lingers close, then roars and morphs quickly before accelerated pursuit',()=>{const {mimic,p}=fixture();spawn(mimic,p);const before={...mimic.state!};expect(mimic.update(121100,[p])).toBeNull();expect(distance(before,mimic.state!)).toBeGreaterThan(0);mimic.reset(1000);linger(mimic,p);const pos={...mimic.state!};p.x=mimic.state!.x;p.y=mimic.state!.y;expect(mimic.update(123299,[p])).toBeNull();expect(distance(pos,mimic.state!)).toBe(0);expect(mimic.drainSounds()).toEqual([]);mimic.update(123300,[p]);expect(mimic.state!.phase).toBe('morph');expect(mimic.drainSounds().map(s=>s.kind)).toEqual(['mimic-roar']);expect(mimic.update(123659,[p])).toBeNull();mimic.update(123660,[p]);expect(mimic.state!.phase).toBe('chase');expect(mimic.update(123760,[p])).toBe('p');expect(mimic.update(123860,[p])).toBeNull();expect(T.chaseStride).toBeGreaterThan(1.6);});
 it('emits one live roar; visible snapshots never replay it',()=>{const {mimic,p}=fixture();morph(mimic,p);expect(mimic.drainSounds().map(s=>s.kind)).toEqual(['mimic-roar']);for(let i=0;i<4;i++)mimic.visibleTo(p);mimic.update(123400,[p]);expect(mimic.drainSounds()).toEqual([]);});
 it('reserves15seconds in darkness and never reappears at a now-observed origin',()=>{const {mimic,p}=fixture();spawn(mimic,p);p.connected=false;mimic.update(121100,[p]);expect(mimic.state?.phase).toBe('retreat');mimic.update(122000,[p]);expect(mimic.visibleTo({...p,connected:true})).toBeNull();p.connected=true;p.x=mimic.state!.originX;p.y=mimic.state!.originY;mimic.update(122100,[p]);expect(mimic.state?.phase).toBe('retreat');mimic.update(136100,[p]);expect(mimic.state).toBeNull();});
 it('retargets invalid targets with warning and pursues a substantially nearer fleeing player',()=>{const {mimic,p}=fixture();morph(mimic,p);mimic.update(123660,[p]);const q={...createPlayer('q','Second'),x:mimic.state!.x+1,y:mimic.state!.y,sprinting:true,vx:6.4};p.x=mimic.state!.x-10;const before={...mimic.state!};mimic.update(124000,[p,q]);expect(mimic.state!.targetId).toBe('q');expect(distance(before,mimic.state!)).toBe(0);expect(mimic.update(124800,[q])).toBeNull();p.zone='asylum';expect(mimic.state!.disguisePlayerId).toBe('p');});
 it('fire, asylum, halo, race and offline players remain protected',()=>{for(const kind of ['fire','asylum','halo','race','offline']){const {mimic,p}=fixture();if(kind==='fire'){p.x=24;p.y=24;}if(kind==='asylum')p.zone='asylum';if(kind==='halo')p.haloUntil=999999;if(kind==='race')p.mode='race';if(kind==='offline')p.connected=false;mimic.update(121000,[p]);expect(mimic.state).toBeNull();}});
 it('rejects catches through geometry and clones visible disguise',()=>{const {mimic,p}=fixture();morph(mimic,p);const visible=mimic.visibleTo(p)!;visible.disguise.hairColor='#000000';expect(mimic.state!.disguise.hairColor).not.toBe('#000000');world.map.solids.push({x:mimic.state!.x-.2,y:mimic.state!.y-1,width:.4,height:2});p.x=mimic.state!.x+.1;mimic.update(123660,[p]);expect(mimic.update(123760,[p])).toBeNull();world.map.solids=[];});
 it('cannot pop into any of eight spread humans’ views, including protected observers',()=>{const {mimic,p}=fixture();const observers=Array.from({length:8},(_,i)=>({...createPlayer(String(i),'Observer'),x:10+(i%4)*19,y:8+Math.floor(i/4)*36,haloUntil:999999}));mimic.update(121000,[p,...observers]);expect(mimic.state).toBeNull();const solo=fixture();spawn(solo.mimic,solo.p);expect(outsideForestView(solo.mimic.state!,solo.p,world.map)).toBe(true);});
 it('bounds desktop, ultrawide and mobile views and accounts for edge clamping',()=>{for(const [w,h] of [[390,339],[1440,600],[3840,720],[600,1200]]){const z=forestCameraZoom(w!,h!);expect(w!/z/32).toBeLessThanOrEqual(FOREST_VIEW.width+.001);expect(h!/z/32).toBeLessThanOrEqual(FOREST_VIEW.height+.001);}expect(outsideForestView({x:35,y:10},{x:1,y:1},world.map)).toBe(false);expect(outsideForestView({x:44,y:10},{x:1,y:1},world.map)).toBe(true);});
});
