import { describe, expect, it } from 'vitest';
import { ForestMimic, MIMIC_TUNING as T } from '../../apps/game-server/src/ForestMimic';
import { getWorld, type WorldDefinition } from '../../packages/config/src/index';
import { createPlayer, distance } from '../../packages/simulation/src/index';
const world: WorldDefinition = { ...getWorld('forest'), map: { ...getWorld('forest').map, solids: [], furniture: [
 {id:'tree',kind:'tree',footprint:{x:43,y:43,width:2,height:3},collider:null,usePoints:[],seats:[]},
] } };
function fixture(){ const mimic=new ForestMimic(world,()=>.5),p={...createPlayer('p','Player'),x:36,y:45};mimic.reset(1000);return {mimic,p}; }
function spawn(m:ForestMimic,p=fixture().p){m.update(121000,[p]);expect(m.state?.phase).toBe('approach');}
function morph(m:ForestMimic,p=fixture().p){spawn(m,p);p.x=m.state!.x-2;p.y=m.state!.y;m.update(121100,[p]);expect(m.state?.phase).toBe('morph');return p;}
describe('room-owned mimic',()=>{
 it('is rarer than wolf/clown and waits without exposed players',()=>{expect(T.intervalMs).toBe(120000);const {mimic,p}=fixture();mimic.update(120999,[p]);expect(mimic.state).toBeNull();p.x=24;p.y=24;mimic.update(121000,[p]);expect(mimic.state).toBeNull();});
 it('captures a cosmetic appearance without aliasing player state',()=>{const {mimic,p}=fixture();spawn(mimic,p);const color=mimic.state!.disguise.hairColor;p.avatar.hairColor='#000000';expect(mimic.state!.disguise.hairColor).toBe(color);expect(mimic.state!.disguisePlayerId).toBe(p.id);});
 it('approaches calmly and cannot catch before a close-range stationary warning',()=>{const {mimic,p}=fixture();spawn(mimic,p);const before={...mimic.state!};expect(mimic.update(121100,[p])).toBeNull();expect(distance(before,mimic.state!)).toBeGreaterThan(0);mimic.reset(1000);morph(mimic,p);const pos={...mimic.state!};p.x=mimic.state!.x;p.y=mimic.state!.y;expect(mimic.update(122699,[p])).toBeNull();expect(distance(pos,mimic.state!)).toBe(0);expect(mimic.update(122700,[p])).toBeNull();expect(mimic.state!.phase).toBe('chase');expect(mimic.update(122800,[p])).toBe('p');expect(mimic.update(122900,[p])).toBeNull();});
 it('emits exactly one live roar; rendering/reconnect snapshots do not replay it',()=>{const {mimic,p}=fixture();morph(mimic,p);expect(mimic.drainSounds().map(s=>s.kind)).toEqual(['mimic-roar']);for(let i=0;i<4;i++)mimic.visibleTo(p);mimic.update(121200,[p]);expect(mimic.drainSounds()).toEqual([]);});
 it('retreats when target disconnects and holds one reserved threat for15seconds',()=>{const {mimic,p}=fixture();spawn(mimic,p);p.connected=false;mimic.update(121100,[p]);expect(mimic.state?.phase).toBe('retreat');mimic.update(122000,[p]);expect(mimic.visibleTo({...p,connected:true})).toBeNull();mimic.update(136099,[p]);expect(mimic.state).not.toBeNull();mimic.update(136100,[p]);expect(mimic.state).toBeNull();});
 it('retargets nearest exposed player, preserves disguise and pauses before chasing',()=>{const {mimic,p}=fixture();morph(mimic,p);mimic.update(122700,[p]);const disguise={...mimic.state!.disguise};const q={...createPlayer('q','Second'),x:mimic.state!.x+1,y:mimic.state!.y};p.zone='asylum';const pos={...mimic.state!};mimic.update(122800,[p,q]);expect(mimic.state!.targetId).toBe('q');expect(mimic.state!.disguise).toEqual(disguise);expect(mimic.update(123600,[q])).toBeNull();expect(distance(pos,mimic.state!)).toBe(0);});
 it('fire/asylum/halo/race/disconnected players cannot be targeted or caught',()=>{for(const kind of ['fire','asylum','halo','race','offline']){const {mimic,p}=fixture();if(kind==='fire'){p.x=24;p.y=24;}if(kind==='asylum')p.zone='asylum';if(kind==='halo')p.haloUntil=999999;if(kind==='race')p.mode='race';if(kind==='offline')p.connected=false;mimic.update(121000,[p]);expect(mimic.state).toBeNull();}});
 it('rejects catches through blocked geometry and clones visible disguise',()=>{const {mimic,p}=fixture();morph(mimic,p);const visible=mimic.visibleTo(p)!;visible.disguise.hairColor='#000000';expect(mimic.state!.disguise.hairColor).not.toBe('#000000');world.map.solids.push({x:mimic.state!.x-.2,y:mimic.state!.y-1,width:.4,height:2});p.x=mimic.state!.x+.1;mimic.update(122700,[p]);expect(mimic.update(122800,[p])).toBeNull();world.map.solids=[];});
});
